In [ ]:
#These are libraries that you should import if needed for your notebook.
#import libraries
#from datascience import *
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Basics

Built-in Data Types
In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

Python has the following data types built-in by default, in these categories:


*  Text or string Type:	  str
   *  Much of the world’s data is text, and a piece of text represented in a computer is called a string. A string can represent a word, a sentence, or even the contents of every book in a library.
*  Numeric Types:	int, float, complex
   *  Integers are called int values in the Python language. They can only represent whole numbers (negative, zero, or positive) that don’t have a fractional component
   * Real numbers are called float values (or floating point values) in the Python language. They can represent whole or fractional numbers but have some limitations.
*  Sequence Types:	list, tuple, range
   * Values can be grouped together into collections, which allows programmers to organize those values and refer to all of them with a single name. By grouping values together, we can write code that performs a computation on many pieces of data at once.
*  Mapping Type:	dict
*  Set Types:	  set, frozenset
*  Boolean Type:	  bool

In [ ]:
print('Goodluck with the workshop')

Goodluck with the workshop


## Operations

Python operators are special symbols (sometimes called keywords) that are used to perform certain most commonly required operations on one or more operands (value, variables, or expressions).

Python language supports the following types of operators:

* Arithmetic Operators

* Comparison (Relational) Operators

* Assignment Operators

* Logical Operators

* Bitwise Operators

* Membership Operators

* Identity Operators

In [ ]:
#Print Hello World
print ('Hello World')

Hello World


In [ ]:
#Print a number
print (10)

10


In [ ]:
#Add two numbers
num1 = 20
num2 = 10
sum = num1 + num2
print(sum)

30


In [ ]:
#Subtract one number from another
num1 = 20
num2 = 10
diff = num1 - num2
print(diff)

10


In [ ]:
#Multiply two numbers
2 * 8

16

In [ ]:
#Multiply two numbers
num1 = 20
num2 = 10
product = num1 * num2
print(product)

200


In [ ]:
#Divide one number by another
20/10

2.0

In [ ]:
#Calculate 2 to the power of 3
2 ** 3

8

## Variables

Variables are containers for storing data values. Unlike other languages, such as Java, Python has no command for declaring a variable, so you create one the moment you first assign a value to it.

* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)
* A variable name cannot be any of the Python keywords.

In [ ]:
#Store the value of 5 in variable a.
a = 5

In [ ]:
#What is the value of  variable a
a

5

In [ ]:
#Multiply variable a by another number
a * 7

35

In [ ]:
#Add a number to  variable a
a + 7

12

In [ ]:
#Change the value of variable a
a = 20

In [ ]:
#Multiply variable a by a number
a * 10

200

In [ ]:
#Add variables a and b.
a = 20
b = 15

In [ ]:
#Store the value of 15 in variable b
b =15

In [ ]:
#Create a new variable (total) and equate that to the value of a and b
a = 20
b = 15
total = a + b
print (total)

35


In [ ]:
#What is the value of total
a + b

35

In [ ]:
#Create a variable (new) and equate that to a string 'Stellenbosch'
new = 'Stellenbosch'

In [ ]:
#Add 5 to variable new


In [ ]:
#Multiply the variable new by a number
new * 5


'StellenboschStellenboschStellenboschStellenboschStellenbosch'

**Class Exercise 1:**

In [ ]:
#15, 40 and 52 respectively
hourly_minimum_wage = 15
hours_per_week = 40
weeks_per_year = 52

In [ ]:
hourly_minimum_wage
hourly_minimum_wage

15

In [ ]:
#Determine the number of working hours in a year, store it in a variable, and output that
hours_per_year = hours_per_week * weeks_per_year
hours_per_year

2080

In [ ]:
#Determine the minimum earning per year
hours_per_year * hourly_minimum_wage

31200

In [ ]:
#Determine the minimum earning per year using the original variables that were defined
hourly_minimum_wage * hours_per_week * weeks_per_year

31200

## Arrays

Arrays represent multiple data elements of the same type using a single name. An array is a special variable, which can hold more than one value at a time.

In [ ]:
#np.array is used to create an array
np.array ([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Equate the above array to A
A = np.array ([1,2,3,4,5,6])

In [ ]:
#Multiply A by a number, what do you notice?
A * 3

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
#Add a number to A, what do you notice?
A + 3

array([4, 5, 6, 7, 8, 9])

In [ ]:
#Use add the elements of A
A + 10

array([11, 12, 13, 14, 15, 16])

**Class Exercise 2:**

In [ ]:
#Create a new array with elements 11, 13, 15 and 17 and store it in variable B
B = np.array ([11,13,15,17])

In [ ]:
#Add A and B, what do you notice?
A = np.array ([1,2,3])
B = np.array ([11,13,15])
A + B

array([12, 15, 18])

In [ ]:
#Create a new variable a and equate that to number
a = 15

In [ ]:
#Add a and B
a + b

20

In [ ]:
#Create two variables a and b and equate that to 9 and 5.
#Then create an array with the first element a+b and second element a*b

a = 9
b = 5
np.array ([a+b, a*b])


array([14, 45])

In [ ]:
#Create a new array with elements 4, 5 and 7; and store it in variable C
C = np.array([4, 5, 7])

In [ ]:
# Display A
A

array([1, 2, 3])

In [ ]:
# print A
print(A)

[1 2 3]


In [ ]:
#Add A and C  .Be mindful of the error
A + C

array([ 5,  7, 10])

## Create a basic array

When it comes to creating a sequence of values, linspace and arange are two commonly used NumPy functions.

Here is the subtle difference between the two functions:

* linspace allows you to specify the number of steps
* arange allows you to specify the size of the steps
The following examples show how to use each function in practice.

### np.arange

The np.arange() function uses the following basic syntax:

np.arange(start, stop, step, …)

where:

* start: The starting value of the sequence
* stop: The end value of the sequence
* step: The spacing between values

In [ ]:
#np.arange can take in 1, 2 or 3 inputs. When it takes one input, it creates an array from 0 as the first element
#with each subsequent element increasing by 1 until it reaches a number less than the input number.
#Write an np.arange command with one input. Let that input be 7.

np.arange (7)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
#What if I wanted the array to start at 1 and end in the value of the input
np.arange (1, 7)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Let's try np.arange with two inputs seperated by a comma. The two inputs can be 1 and 8.
np.arange (1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Create an array that starts with 200 and ends 211
np.arange (200, 212,1)

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211])

In [ ]:
#Let's try np.arange with two inputs seperated by a comma. The two inputs can be 1 and 8.  np.arange(start, stop, step, …)
np.arange(1,8,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [ ]:
#Create two arrays using np.arange. The first array should use one input(5) and the second one using two inputs (10 and 13).
#Now, use np.append with two inputs. The two inputs are the arrays from above.
#What does np.append do

first = np.arange(5)
second = np.arange(10,13)
Third = np.append(first, second)

In [ ]:
### np.linspace

#The np.linspace() #function uses the following basic syntax:

#np.linspace #(start, stop, num, …)

#where:

#* start: The starting value of the sequence
#* stop: The end value of the sequence
#* num: the number of values to generate


In [ ]:
#create sequence of 11 evenly spaced values between 0 and 20
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [ ]:
a = np.linspace(0, 10, 3)
print(a)

[ 0.  5. 10.]


In [ ]:
print(a.dtype)
a.dtype

float64


dtype('float64')

In [ ]:
# Change the dtype to int
a_int = np.linspace(0, 10, 3, dtype=int)
print(a_int)

[ 0  5 10]


In [ ]:
#print(a_int.dtype)
print(a_int.dtype)


int64



**Class Exercise 3**:

Create an array that ranges from 3 to 10 (inclusive). Another from 13 to 20 (inclusive). Add the two arrays.

In [ ]:
A1 =np.arange(3,11)
A2 = np.arange(13,21)
A1+A2

array([16, 18, 20, 22, 24, 26, 28, 30])

Generate a reverse order array with np.arange() from 9 to 2 with a step size of 2

In [ ]:
print(np.arange(9, 2, -2))
# [9 7 5 3]

[9 7 5 3]


# TAKE-HOME EXERCISE 1

**Complete the following take-home exercise for the next workshop session:**

You have a class of 10 students. Each student has completed two tests and one exam. The total scores for the tests were 70 and 80 respectively and the total score for the exam was 120. Test one and two each make up 25% of the final mark for the module, while the exam makes up the rest.

The scores for the students, out ouf their respective totals, are as follows...

For test 1 = 65, 63, 68, 40, 55, 43, 69, 52, 51, 48

For test 2 = 77, 79, 70, 35, 50, 46, 80, 56, 56, 52

For the exam = 110, 109, 100, 55, 60, 61, 115, 96, 99, 75


Make use of arrays to caclulate the following:
1.   The final mark (%) of each student.
2.   The class average (%) for each assesment as well as for the module.
3.   BONUS: Give the hightest and lowest final marks for the module (use Google).



# Tables

Tables are a fundamental object type for representing data sets. A table can be viewed in two ways:

* a sequence of named columns (i.e features or attributes) that each describe a single aspect of all entries in a data set, or

* a sequence of rows (data points or data instances) that each contain all information about a single entry in a data set.....

In [ ]:
#Upload olympics2024.csv file
from google.colab import files
uploaded = files.upload()

Saving olympics2024.csv to olympics2024.csv


In [ ]:
#Read the file into a table called olympics
olympics = pd.read_csv('olympics2024.csv')

In [ ]:
#Output the table, olympics to the screen
print(olympics)

    Rank        Country Country Code      Continent  Gold  Silver  Bronze  \
0      1  United States           US  North America    40      44      42   
1      2          China          CHN           Asia    40      27      24   
2      3          Japan          JPN           Asia    20      12      13   
3      4      Australia          AUS        Oceania    18      19      16   
4      5         France          FRA         Europe    16      26      22   
..   ...            ...          ...            ...   ...     ...     ...   
86    84           Peru          PER  South America     0       0       1   
87    84          Qatar          QAT           Asia     0       0       1   
88    84      Singapore          SIN           Asia     0       0       1   
89    84       Slovakia          SVK         Europe     0       0       1   
90    84         Zambia          ZAM         Africa     0       0       1   

    Total    Population  GDP per capita (current US$)  
0     126  3.349149

In [ ]:
#Show only the top three rows of the table
olympics.head(3)

Rank        Country Country Code      Continent  Gold  Silver  Bronze  \
0     1  United States           US  North America    40      44      42   
1     2          China          CHN           Asia    40      27      24   
2     3          Japan          JPN           Asia    20      12      13   

   Total    Population  GDP per capita (current US$)  
0    126  3.349149e+08                   71972.64137  
1     91  1.410710e+09                   11689.34581  
2     45  1.245166e+08                   37673.38470

In [ ]:
#Show only the top ten rows of the table
olympics.head(10)

Rank        Country Country Code      Continent  Gold  Silver  Bronze  \
0     1  United States           US  North America    40      44      42   
1     2          China          CHN           Asia    40      27      24   
2     3          Japan          JPN           Asia    20      12      13   
3     4      Australia          AUS        Oceania    18      19      16   
4     5         France          FRA         Europe    16      26      22   
5     6    Netherlands          NED         Europe    15       7      12   
6     7  Great Britain          GBG         Europe    14      22      29   
7     8    South Korea          KOR           Asia    13       9      10   
8     9          Italy          ITA         Europe    12      13      15   
9    10        Germany          GER         Europe    12      13       8   

   Total    Population  GDP per capita (current US$)  
0    126  3.349149e+08                   71972.64137  
1     91  1.410710e+09                   11689.34581  
2     45  1.245166e+08                   37673.38470  
3     53  2.663854e+07                   59480.90144  
4     64  6.817023e+07                   41738.60442  
5     34  1.787949e+07                   56585.69168  
6     65  6.697000e+07                   46125.26000  
7     32  5.171262e+07                   32853.05860  
8     40  5.876115e+07                   35095.94639  
9     33  8.448227e+07                   49289.02237

In [ ]:
#Show all rows of the table excluding the last 10
olympics.head(-10)

Rank        Country Country Code      Continent  Gold  Silver  Bronze  \
0      1  United States           US  North America    40      44      42   
1      2          China          CHN           Asia    40      27      24   
2      3          Japan          JPN           Asia    20      12      13   
3      4      Australia          AUS        Oceania    18      19      16   
4      5         France          FRA         Europe    16      26      22   
..   ...            ...          ...            ...   ...     ...     ...   
76    74       Mongolia          MGL           Asia     0       1       0   
77    74         Panama          PAN  North America     0       1       0   
78    79     Tajikistan          TJK           Asia     0       0       3   
79    80        Albania          ALB         Europe     0       0       2   
80    80        Grenada          GRN  North America     0       0       2   

    Total    Population  GDP per capita (current US$)  
0     126  3.349149e+08                  71972.641370  
1      91  1.410710e+09                  11689.345810  
2      45  1.245166e+08                  37673.384700  
3      53  2.663854e+07                  59480.901440  
4      64  6.817023e+07                  41738.604420  
..    ...           ...                           ...  
76      1  3.447157e+06                   4762.513793  
77      1  4.468087e+06                  16255.370140  
78      3  1.014354e+07                    984.694648  
79      2  2.745972e+06                   6458.868963  
80      2  1.261830e+05                   9512.406197  

[81 rows x 10 columns]

In [ ]:
#Show only the last five rows of the table
olympics.tail(5)

Rank    Country Country Code      Continent  Gold  Silver  Bronze  Total  \
86    84       Peru          PER  South America     0       0       1      1   
87    84      Qatar          QAT           Asia     0       0       1      1   
88    84  Singapore          SIN           Asia     0       0       1      1   
89    84   Slovakia          SVK         Europe     0       0       1      1   
90    84     Zambia          ZAM         Africa     0       0       1      1   

    Population  GDP per capita (current US$)  
86  34352719.0                   6949.323111  
87   2716391.0                  67370.554620  
88   5917648.0                  76062.578980  
89   5426740.0                  21290.114290  
90  20569737.0                   1237.426046

In [ ]:
#Show only the last ten rows of the table
olympics.tail(10)

Rank               Country Country Code      Continent  Gold  Silver  \
81    80              Malaysia          MAS           Asia     0       0   
82    80           Puerto Rico          PUR  North America     0       0   
83    84            Cape Verde          CPV         Africa     0       0   
84    84           Ivory Coast          CIV         Africa     0       0   
85    84  Refugee Olympic Team          EOR         Global     0       0   
86    84                  Peru          PER  South America     0       0   
87    84                 Qatar          QAT           Asia     0       0   
88    84             Singapore          SIN           Asia     0       0   
89    84              Slovakia          SVK         Europe     0       0   
90    84                Zambia          ZAM         Africa     0       0   

    Bronze  Total  Population  GDP per capita (current US$)  
81       2      2  34308525.0                  11214.586380  
82       2      2   3205691.0                  33802.136980  
83       1      1    598682.0                   3744.982919  
84       1      1  28873034.0                   2505.987442  
85       1      1         NaN                           NaN  
86       1      1  34352719.0                   6949.323111  
87       1      1   2716391.0                  67370.554620  
88       1      1   5917648.0                  76062.578980  
89       1      1   5426740.0                  21290.114290  
90       1      1  20569737.0                   1237.426046

In [ ]:
print('SESSION 1 COMPLETED FROM STELLENBOSCH WORKSHOP')

SESSION 1 COMPLETED FROM STELLENBOSCH WORKSHOP
